-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:da4112349f33db9a97f39a65399a480f$
-- 

--return {
PauseAtlasDescriptor = {
    texture = 'button_pause.png',
    frames = {
            {
                name = "button_pause_down.png",
                spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
                uvRect = { u0 = 0.015625, v0 = 0.0078125, u1 = 0.640625, v1 = 0.320312 },
                spriteSourceSize = { width = 40, height = 40 },
                spriteTrimmed = false,
                textureRotated = false
            },
            {
                name = "button_pause_up.png",
                spriteColorRect = { x = 0, y = 0, width = 40, height = 40 },
                uvRect = { u0 = 0.015625, v0 = 0.328125, u1 = 0.640625, v1 = 0.640625 },
                spriteSourceSize = { width = 40, height = 40 },
                spriteTrimmed = false,
                textureRotated = false
            },
        }
    }
